title       = "tc"
baseURL     = "https://topcoder-cli.tamnd.com/"
description = "Browse TopCoder challenges and member profiles"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/topcoder-cli"
